# Generated by Django 4.2.6 on 2023-10-18 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PsyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_text', models.CharField(max_length=100)),
                ('result_img', models.ImageField(upload_to='images/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='psytest.answer')),
                ('psytest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='psytest.psytest')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('psytest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='psytest.psytest')),
            ],
        ),
    ]
