# Generated by Django 4.2.6 on 2023-10-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0004_alter_psytest_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='psytest',
            name='writer_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
