# Generated by Django 4.2.6 on 2023-10-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0005_psytest_writer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psytest',
            name='writer_name',
        ),
    ]
